# Generated by Django 5.2.7 on 2025-11-05 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('EMPLOYEE', 'EMPLOYEE'), ('EXECUTIVE', 'EXECUTIVE'), ('MANAGER', 'MANAGER')], default='EMPLOYEE', max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
